### ISSUE TITLE
Time Series Extraction

### ISSUE THREAD

**Issue by goastler** [goastler/uea-tsc#20]
Utilities.extractTimeSeries includes the class value in the extraction of the time series. This should be dropped.

**Comment by TonyBagnall** [comment]
does it? Initially thought it was ok but yes, if the class is at the end it will overwrite the value . Currently this
![image](https://user-images.githubusercontent.com/9594042/52340501-ccc34e00-2a07-11e9-868e-13391f81a9e1.png)
but should be this
![image](https://user-images.githubusercontent.com/9594042/52340541-e49ad200-2a07-11e9-8fff-850d3e58aec3.png)

I think

**Comment by TonyBagnall** [comment]
the only place this code is called is in 
measures\DistanceMeasure.java

**Comment by TonyBagnall** [comment]
@goastler could that explain the failure of TAA?

**Comment by goastler** [comment]
@TonyBagnall see issue #17

**Comment by goastler** [comment]
@TonyBagnall fixed in #21
